In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from python_speech_features import mfcc
from python_speech_features import logfbank
import scipy.io.wavfile as wav
import os

In [84]:
from pydub import AudioSegment

def mp3towav(dirOrigen, dirDest):
    dirs = os.listdir(dirOrigen)
    for i in range(len(dirs)):
        audSeg = AudioSegment.from_mp3(os.path.join(dirOrigen, dirs[i]))
        dst=os.path.join(dirDest, dirs[i])[:-4]
        audSeg.export(dst, format="wav")
    return 'Done'

In [8]:
#No ejecutar de nuevo
#mp3towav('OtherVoices', 'OtherVoicesWav')

'Done'

In [5]:
def feature_extraction(path):
    (rate, signal) = wav.read(path)
    mfcc0 = mfcc(signal, rate, nfft=1200)

    return mfcc0

In [92]:
mfcc1 = feature_extraction('VoiceJhon_2seg/voz1')
mfcc1.shape

(399, 13)

In [33]:
mfcc1[200]

array([15.14119547, 33.804992  , 17.598914  , -1.49570858,  7.18107174,
        7.31387587, 16.6244021 , -2.15624084,  3.754287  , -7.61730031,
       13.50118616,  6.47892846,  8.83158458])

In [93]:
mfcc2 = feature_extraction('VoiceJhon_2seg/voz13')
mfcc2.shape

(399, 13)

In [34]:
mfcc2[200]

array([ 13.43684901,  29.10523882,  10.86748652,  -0.86673965,
        11.54582094,   9.74162424,   1.33894264, -17.19453021,
        -5.99656932, -11.55575653,  -6.98856548, -18.95479844,
        -9.5064889 ])

In [63]:
len(mfcc1)

381

In [74]:
def mfcc_min(path_dir_1):
    min = 1000
    name = ''
    cont = os.listdir(path_dir_1)
    for i in range(len(cont)):
        feature = feature_extraction(os.path.join(path_dir_1, cont[i]))
        if (len(feature)< min):
            min = len(feature)
            name = os.path.join(path_dir_1, cont[i])
    print(min)
    print(name)

def mfcc_max(path_dir_1):
    max = 0
    name = ''
    cont = os.listdir(path_dir_1)
    for i in range(len(cont)):
        feature = feature_extraction(os.path.join(path_dir_1, cont[i]))
        if (len(feature)> max):
            max = len(feature)
            name = os.path.join(path_dir_1, cont[i])
    print(max)
    print(name)


In [75]:
max = mfcc_max('VozJhon')

971
VozJhon/voz2.wav


In [76]:
min = mfcc_min('VozJhon')

279
VozJhon/voz74.wav


In [54]:
mfcc1[0]

array([-3.60436534e+01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -3.43216945e-14,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  9.64028692e-15,  0.00000000e+00,
        0.00000000e+00])

In [60]:
matriz = np.zeros((2,381,13), float)
matriz[0]=mfcc1

In [29]:
def cut_audio_Jh(dirOrigen,dirDest):
    dirs = os.listdir(dirOrigen)
    for i in range(len(dirs)):
        audSeg = AudioSegment.from_wav(os.path.join(dirOrigen, dirs[i]))
        if(len(audSeg)<3000):
            os.remove(os.path.join(dirOrigen, dirs[i]))
        else:
            audSeg=audSeg[2000:4000]
        dst=os.path.join(dirDest, dirs[i])[:-4]
        audSeg.export(dst, format="wav")
    return 'Done'

In [30]:
cut_audio_Jh('newrecordjhon', 'VoiceJhon_2seg')

'Done'

In [10]:
def cut_audio_Oh(dirOrigen,dirDest):
    dirs = os.listdir(dirOrigen)
    for i in range(len(dirs)):
        audSeg = AudioSegment.from_wav(os.path.join(dirOrigen, dirs[i]))
        if(len(audSeg)<=3000):
            audSeg=audSeg[500:2500]
        else:
            audSeg=audSeg[1000:3000]
        dst=os.path.join(dirDest, dirs[i])
        audSeg.export(dst, format="wav")
    return 'Done'

In [74]:
cut_audio_Oh('OtherVoicesWav', 'OtherVoices_2seg')

'Done'

In [85]:
dir = os.listdir('OtherVoices_2seg')
len(dir)

350

In [84]:
dir = os.listdir('OtherVoices_2seg')
cont=0
for i in range(len(dir)):
    audSeg = AudioSegment.from_wav(os.path.join('OtherVoices_2seg', dir[i]))
    if(len(audSeg)==2000):
        cont+=1
cont


350

In [87]:
dir = os.listdir('VoiceJhon_2seg')
cont=0
for i in range(len(dir)):
    audSeg = AudioSegment.from_wav(os.path.join('VoiceJhon_2seg', dir[i]))
    if(len(audSeg)==2000):
        cont+=1
cont


45

In [86]:
dir = os.listdir('VoiceJhon_2seg')
len(dir)

45

In [42]:
dirs = os.listdir('VoiceJhon_2seg')
cont=0
names=[]
for i in range(len(dirs)):
    audSeg = AudioSegment.from_wav(os.path.join('VoiceJhon_2seg', dirs[i]))
    if(len(audSeg)==2000):
        cont+=1

In [28]:
cont=0 #Eliminar audios
for i in range(len(names)):
    os.remove(names[i])
    cont+=1

In [85]:
def feature_extraction(path):
    (rate, signal) = wav.read(path)
    mfcc0 = mfcc(signal, rate, nfft=1200)

    return mfcc0

In [86]:
def all_features_extraction(dir1, dir2):
    contJ=0
    contO=0
    n = len(os.listdir(dir1))+len(os.listdir(dir2))

    matriz = np.zeros((n,199,13), float)
    labels = np.empty(n)
    cont1 = os.listdir(dir1)
    cont2 = os.listdir(dir2)
    for i in range(len(cont1)):
        feature = feature_extraction(os.path.join(dir1, cont1[i]))
        if(len(feature) == 399):
            matriz[i]=feature[:199]
            labels[i] = 1
            contJ +=1
    for j in range(len(cont2)):
        feature = feature_extraction(os.path.join(dir2, cont2[j]))
        if(len(feature)== 199):
            matriz[45+j]=feature
            labels[45+j] = 0
            contO +=1
        
    return contJ, contO, matriz, labels

In [87]:
dirJhon='VoiceJhon_2seg'
dirOther = 'OtherVoices_2seg'
contJ, contO, matrizC, labels= all_features_extraction(dirJhon, dirOther)#Se extraen las caracteristicas en la matriz


In [88]:
labels=np.reshape(labels, (-1,1))

In [89]:
labels.shape

(170, 1)

In [74]:
max = 0
min = -99999
for i in matrizC:
    if(i.max()>max):
        max = i.max()
    if(i.min()>min):
        min = i.min()
max, min

(96.12709967276717, 0.0)

In [75]:
matrizC[0]

array([[  8.57754622,   3.39136326,  -2.61921978, ...,   2.75746364,
          6.12609392,   9.85694873],
       [  7.96403323,  11.85066587,  -4.60877263, ...,  -1.38629058,
          0.66782372,  19.03082597],
       [  8.33336549,  15.89332602,  -0.14276764, ...,   4.54324448,
          2.52336026,  19.00251607],
       ...,
       [ 14.73310211,  39.6398267 ,  18.30634287, ...,  -2.72009414,
         -3.96143925,  12.53470694],
       [ 15.00131775,  51.42631925,  24.40467547, ...,   2.759048  ,
         -7.55097065,  22.02236197],
       [ 15.74739734,  53.50284924,  30.19873327, ...,   5.94220101,
        -11.07627277,  20.25377208]])

In [90]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(matrizC, labels, test_size=0.2, random_state=23)

In [11]:
x_train.shape

(160, 199, 13)

In [12]:
x_test.shape

(54, 199, 13)

In [91]:
X_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1]*x_train.shape[2]))
X_test = np.reshape(x_test, (x_test.shape[0],x_test.shape[1]*x_test.shape[2]))

In [14]:
X_train.shape

(160, 2587)

In [92]:
#Estandarizar matriz de caracteristicas
from sklearn.preprocessing import StandardScaler

scTrain=StandardScaler()
scTrain.fit(X_train)
X_train_st=scTrain.transform(X_train)

In [79]:
X_train_st[0]

array([ 0.41181959,  2.32463631, -0.51658637, ...,  0.35843882,
       -0.21026235,  0.39062735])

In [93]:
scTest=StandardScaler()
scTest.fit(X_test)
X_test_std=scTest.transform(X_test)

In [94]:
from keras.utils import np_utils

nclasses = 2
Y_train = np_utils.to_categorical(y_train,nclasses)
Y_test = np_utils.to_categorical(y_test,nclasses)

(54, 1)

In [95]:
input_dim = X_train_st.shape[1]
output_dim = Y_train.shape[1]

In [107]:
from tensorflow.keras import datasets, Sequential
from tensorflow.keras.layers import Flatten, Dense

modelo=Sequential()
modelo.add( Dense(50, input_dim=input_dim, activation='relu')) # 15 es el numero de neuronas de la capa oculta
modelo.add( Dense(output_dim, activation='softmax'))

In [108]:
modelo.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [109]:
modelo.fit(X_train_st, Y_train, epochs=10)

Epoch 1/10
5/5 [==============================] - 1s 8ms/step - loss: 0.4766 - accuracy: 0.7721
Epoch 2/10
5/5 [==============================] - 0s 9ms/step - loss: 0.0087 - accuracy: 1.0000
Epoch 3/10
5/5 [==============================] - 0s 9ms/step - loss: 5.2302e-04 - accuracy: 1.0000
Epoch 4/10
5/5 [==============================] - 0s 10ms/step - loss: 1.0102e-04 - accuracy: 1.0000
Epoch 5/10
5/5 [==============================] - 0s 8ms/step - loss: 3.9709e-05 - accuracy: 1.0000
Epoch 6/10
5/5 [==============================] - 0s 8ms/step - loss: 2.4395e-05 - accuracy: 1.0000
Epoch 7/10
5/5 [==============================] - 0s 9ms/step - loss: 1.7766e-05 - accuracy: 1.0000
Epoch 8/10
5/5 [==============================] - 0s 7ms/step - loss: 1.4748e-05 - accuracy: 1.0000
Epoch 9/10
5/5 [==============================] - 0s 10ms/step - loss: 1.2987e-05 - accuracy: 1.0000
Epoch 10/10
5/5 [==============================] - 0s 8ms/step - loss: 1.2013e-05 - accuracy: 1.0000


In [110]:
p=modelo.evaluate(X_test,Y_test)
p

2/2 [==============================] - 0s 6ms/step - loss: 0.1351 - accuracy: 1.0000


[0.13508331775665283, 1.0]

In [111]:
def prueba(path):
    mfff=feature_extraction(path)
    if(len(mfff) == 399):
        mfff=mfff[:199]
        mfff_ = np.reshape(mfff, (mfff.shape[0]*mfff.shape[1]))
        mff_ = np.reshape(mfff_, (1,-1))
    else:
        mfff_ = np.reshape(mfff, (mfff.shape[0]*mfff.shape[1]))
        mff_ = np.reshape(mfff_, (1,-1))
    return mff_

In [42]:
X_test_std[22:23].shape

(1, 2587)

In [97]:
sc=StandardScaler()

mff_std=scTrain.transform(mff_)

In [98]:
mff_std.shape

(1, 2587)

In [112]:
Y_pred=modelo.predict(X_test_std[22:23])
Y_pred

1/1 [==============================] - 0s 141ms/step


array([[9.9990535e-01, 9.4598727e-05]], dtype=float32)

In [118]:
m1 = prueba('extraother2seg/sample-000198')
#m1 = prueba('VoiceJhon_2seg/voz10')

In [27]:
m1.shape

(1, 2587)

In [119]:
Y_pred=modelo.predict(m1)
Y_pred

1/1 [==============================] - 0s 58ms/step


array([[1., 0.]], dtype=float32)

In [47]:
for i in range(len(Y_pred+1)):
  if(Y_pred[0,i]<0.5):
    Y_pred[0,i]=0
Y_pred

array([[0., 1.]], dtype=float32)

In [103]:
import pyaudio
import wave


def grabacion(pathDest):
    Format=pyaudio.paInt16
    Channels=1
    Rate=44100
    Chunk=1024
    Duracion=5

    audio=pyaudio.PyAudio()

    stream=audio.open(format=Format, channels=Channels,
                        rate=Rate, input=True,
                        frames_per_buffer=Chunk)

    print('grabando....')
    frames=[]

    for i in range(0,int(Rate/Chunk*Duracion)):
        data=stream.read(Chunk)
        frames.append(data)
    print('grabacion terminada')


    stream.stop_stream()
    stream.close()
    audio.terminate()

    waveFile=wave.open(pathDest, 'wb')
    waveFile.setnchannels(Channels)
    waveFile.setsampwidth(audio.get_sample_size(Format))
    waveFile.setframerate(Rate)
    waveFile.writeframes(b''.join(frames))
    waveFile.close()
    print('Guardado')

    print('Recortando')
    audSeg = AudioSegment.from_wav(pathDest)
    audSeg = audSeg[2000:4000]
    dst='grabaciones/grabacion2seg.wav'
    audSeg.export(dst, format="wav")
    print('Recortado')
    
    features = feature_extraction(dst)
    mfff_ = np.reshape(features, (features.shape[0]*features.shape[1]))
    mff_ = np.reshape(mfff_, (1,-1))
    print('Caracteristicas extraidas')

    print('Eliminando archivos')

    #os.remove(dst)
    #os.remove(pathDest)

    return mff_


    

In [132]:
features = grabacion('grabaciones/grabacion.wav')

ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'


grabando....
grabacion terminada
Guardado
Recortando
Recortado
Caracteristicas extraidas
Eliminando archivos


In [126]:
features.shape

(1, 2587)

In [133]:
Y_pred=modelo.predict(features)
Y_pred

1/1 [==============================] - 0s 103ms/step


array([[1.0000000e+00, 1.1120673e-29]], dtype=float32)

In [34]:
for i in range(len(Y_pred+1)):
  if(Y_pred[0,i] < 0.5):
    Y_pred[0,i]=0
Y_pred

array([[9.9999940e-01, 6.3333454e-07]], dtype=float32)

In [ ]:
# serializa el modelo para JSON
model_json = model_optimizer.to_json()
with open("model.json", "w") as json_file:
  json_file.write(model_json)
#serializan los pesos (weights) para HDF5
model_optimizer.save_weights("model.h5")

In [ ]:
from tensorflow.keras.models import model_from_json 

# carga el json y crea el modelo
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
 
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# se cargan los pesos (weights) en el nuevo modelo
loaded_model.load_weights("model.h5")
print("Modelo cargado desde el PC")
# se evalua el modelo cargado con los datos de los test
loaded_model.compile(optimizer = "adam", loss = "categorical_crossentropy", metrics = ["accuracy"])
score = loaded_model.evaluate(X_test, Y_test, verbose=0)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

In [ ]:
print('git')

In [2]:
import serial